---
name: bazzite-deck
description: bazzite-deck with modifications.

base-image: ghcr.io/ublue-os/bazzite-deck
image-version: stable-41

stages:
  - name: builder
    from: ghcr.io/ublue-os/bazzite-deck:stable-41
    modules:
      - type: rpm-ostree
        install:
          - git
          - cmake
          - gcc-c++
          - extra-cmake-modules
          - qt6-qtbase-devel
          - qt6-qtbase-private-devel
          - qt6-qtdeclarative-devel
          - qt6-qtsvg-devel
          - qt6-qttools-devel
          - kf6-kcmutils-devel
          - kf6-kconfig-devel
          - kf6-kconfigwidgets-devel
          - kf6-kcoreaddons-devel
          - kf6-kguiaddons-devel
          - kf6-ki18n-devel
          - kf6-kiconthemes-devel
          - kf6-kwindowsystem-devel
          - kf6-frameworkintegration-devel 
          - kf6-kirigami-devel
          - kdecoration-devel
          - kwin-devel
          - kf6-kcrash-devel
          - kf6-kglobalaccel-devel
          - kf6-kio-devel
          - kf6-kservice-devel
          - kf6-knotifications-devel
          - libepoxy-devel
          - wayland-devel

      - type: script
        no-cache: true
        snippets:
          - |
            cd /tmp
            git clone https://github.com/paulmcauley/klassy
            cd klassy
            git checkout plasma6.2
            mkdir build
            cd build
            cmake ../ -DCMAKE_INSTALL_PREFIX=/usr
            make -j$(nproc)
            mkdir -p /tmp/staged-klassy/usr
            make install DESTDIR=/tmp/staged-klassy
            cp -r /tmp/staged-klassy/usr /usr/

      - type: script
        no-cache: true
        snippets:
          - |
            cd /tmp
            git clone https://github.com/taj-ny/kwin-effects-forceblur
            cd kwin-effects-forceblur
            mkdir build
            cd build
            cmake ../ -DCMAKE_INSTALL_PREFIX=/usr
            make -j$(nproc)
            mkdir -p /tmp/staged-forceblur/usr
            make install DESTDIR=/tmp/staged-forceblur
            cp -r /tmp/staged-forceblur/usr /usr/

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/lihaohong/yazi/repo/fedora-%OS_VERSION%/lihaohong-yazi-fedora-%OS_VERSION%.repo
    install:
      - corectrl # AMDGPU util
      - alacritty # Terminal

      - nu # My Shell
      - starship # Prompt
      - atuin # Shell History
      - zoxide # Magic cd

      - helix # Editor
      - yazi # File Manager
      - btop # System Monitor
      - pipx # Handy to have
      
      - syncthing # Local File Sync

      # Virtualization
      - qemu
      - edk2-ovmf
      - virt-manager
      - virt-viewer

      - obs-studio

    remove:
      - kwrite
      - kfind
      - khelpcenter
      - kate
      - kate-krunner-plugin
      - kate-plugins
      - kjournald
      - kjournald-libs
      - krfb
      - krfb-libs
      - kdebugsettings
      - plasma-systemmonitor
      - nvtop
      - firewall-config

      # "These are installed in kinotie. But removed in Bazzite."
      # - firefox
      # - firefox-langpacks
      # - plasma-drkonqi
      # - htop
      # - konsole

      - ptyxis # Default Bazzite Terminal.

  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)"
      install:
        - app.zen_browser.zen 
        - org.gnome.Loupe
        - com.github.dynobo.normcap
        - com.usebottles.bottles
        - dev.vencord.Vesktop
        - fr.handbrake.ghb
        - com.ranfdev.DistroShelf
        - io.github.ungoogled_software.ungoogled_chromium
        - md.obsidian.Obsidian
        - org.archivekeep.ArchiveKeep
        - org.gimp.GIMP
        - org.gimp.GIMP.HEIC
        - org.signal.Signal
        - org.telegram.desktop
        - org.telegram.desktop.webview
        - org.fooyin.fooyin
        - org.blender.Blender
        - net.nokyan.Resources
        - io.gitlab.liferooter.TextPieces
        - io.github.nokse22.asciidraw
        - io.github.nokse22.Exhibit
        - io.github.nate_xyz.Chromatic
        - io.bassi.Amberol
        - io.github.TheWisker.Cavasik
        - io.github.flattool.Warehouse
        - io.gitlab.theevilskeleton.Upscaler
        - app.drey.Warp
        - app.fotema.Fotema
        - app.fotema.Fotema.HEIC
        - com.cassidyjames.butler
        - com.konstantintutsch.Lock
        - com.protonvpn.www
        - com.rafaelmardojai.Blanket
        - com.system76.Popsicle
        - de.haeckerfelix.AudioSharing
        - dev.geopjr.Calligraphy
        - fr.romainvigier.MetadataCleaner
        - fm.reaper.Reaper
        - io.github.input_leap.input-leap
        - org.gnome.Papers
        - org.gnome.Showtime
        - org.gnome.baobab
        - org.kde.kdenlive
        - org.kde.krita
        - org.nickvision.tubeconverter
        - org.musicbrainz.Picard
        - org.remmina.Remmina
        - org.onlyoffice.desktopeditors
        - xyz.safeworlds.hiit
        - io.unobserved.furtherance

  - type: signing
