---
name: cosmic
description: cosmic-atomic-main with modifications.
    
base-image: ghcr.io/ublue-os/cosmic-atomic-main
image-version: latest

stages:
  - name: cosmic-ext-extra-sessions
    from: docker.io/library/rust
    modules:
      - type: script
        snippets:
          - git clone https://github.com/Drakulix/cosmic-ext-extra-sessions.git
          - git -C cosmic-ext-extra-sessions submodule update --init
          - cargo install just
          - cd cosmic-ext-extra-sessions && just build && just install-niri
          - sed -i 's|/usr/local/bin/start-cosmic-ext-niri|/usr/bin/start-cosmic-ext-niri|g' /usr/local/share/wayland-sessions/cosmic-ext-niri.desktop
modules:
  - type: copy
    from: cosmic-ext-extra-sessions
    src: /usr/local/bin/cosmic-ext-alternative-startup
    dest: /usr/bin/cosmic-ext-alternative-startup

  - type: copy
    from: cosmic-ext-extra-sessions
    src: /usr/local/share/wayland-sessions/cosmic-ext-niri.desktop
    dest: /usr/share/wayland-sessions/cosmic-ext-niri.desktop

  - type: copy
    from: cosmic-ext-extra-sessions
    src: /usr/local/bin/start-cosmic-ext-niri
    dest: /usr/bin/start-cosmic-ext-niri

  - type: files
    files:
      - source: system
        destination: /

  - type: script

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/lihaohong/yazi/repo/fedora-%OS_VERSION%/lihaohong-yazi-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/yalter/niri-git/repo/fedora-%OS_VERSION%/yalter-niri-fedora-%OS_VERSION%.repo

    install:
      # AMDGPU
      - corectrl

      # Terminal
      - alacritty

      - nu
      - dash
      - starship
      - atuin
      - zoxide

      - helix
      - yazi
      - btop
      
      # Virtualization
      - qemu
      - edk2-ovmf
      - virt-manager
      - virt-viewer

      # Streaming
      - obs-studio

      # Compositor and friends.
      - niri
      - nautilus
      - sushi

      # Disks
      - gdisk
      - btrfs-progs

      # Android
      - waydroid

      # Microcompositors & Gaming
      - gamescope
      - gamemode

  - type: signing
