---
name: kinoite-nvidia-open
description: kinoite-main with modifications.

base-image: quay.io/fedora-ostree-desktops/kinoite
image-version: 44
stages:
  - name: better-blur-dx
    from: quay.io/fedora-ostree-desktops/kinoite:44
    modules:
      - type: dnf
        install:
          packages:
            - git
            - cmake
            - extra-cmake-modules
            - gcc-g++
            - kf6-kwindowsystem-devel
            - plasma-workspace-devel
            - libplasma-devel
            - qt6-qtbase-private-devel
            - qt6-qtbase-devel
            - kwin-devel
            - kf6-knotifications-devel
            - kf6-kio-devel
            - kf6-kcrash-devel
            - kf6-ki18n-devel
            - kf6-kguiaddons-devel
            - libepoxy-devel
            - kf6-kglobalaccel-devel
            - kf6-kcmutils-devel
            - kf6-kconfigwidgets-devel
            - kf6-kdeclarative-devel
            - kdecoration-devel
            - wayland-devel
            - libdrm-devel
            - rpm-build
      - type: script
        snippets:
          - |
            set -euo pipefail
            git clone https://github.com/xarblu/kwin-effects-better-blur-dx
            cd kwin-effects-better-blur-dx
            mkdir build && cd build
            cmake .. -DCMAKE_INSTALL_PREFIX=/usr
            make -j$(nproc)
            cpack -V -G RPM
            mkdir -p /output
            cp kwin-better-blur-dx.rpm /output/

modules:
  - from-file: base/common.yml

  - from-file: base/kinoite.yml

  - from-file: base/nvidia.yml

  - type: os-release
    properties:
      PRETTY_NAME: BlueBuild OS for Nvidia - Kinoite (FROM Fedora Kinoite)

  - from-file: base/post-build.yml

  - type: files
    files:
      - source: system
        destination: /

  - type: script

  - type: copy
    from: better-blur-dx
    src: /output/kwin-better-blur-dx.rpm
    dest: /tmp/kwin-better-blur-dx.rpm

  - type: script
    snippets:
      - rpm -ivh /tmp/kwin-better-blur-dx.rpm
      - rm -f /tmp/kwin-better-blur-dx.rpm

  - type: dnf
    repos:
      files:
        - https://copr.fedorainfracloud.org/coprs/scottames/ghostty/repo/fedora-%OS_VERSION%/scottames-ghostty-fedora-%OS_VERSION%.repo
        - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
        - https://copr.fedorainfracloud.org/coprs/lihaohong/yazi/repo/fedora-%OS_VERSION%/lihaohong-yazi-fedora-%OS_VERSION%.repo
        - https://repository.mullvad.net/rpm/stable/mullvad.repo
        - https://copr.fedorainfracloud.org/coprs/sneexy/zen-browser/repo/fedora-%OS_VERSION%/sneexy-zen-browser-fedora-%OS_VERSION%.repo
        - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
        - https://copr.fedorainfracloud.org/coprs/yalter/niri-git/repo/fedora-%OS_VERSION%/yalter-niri-fedora-%OS_VERSION%.repo
      keys:
        - https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
    install:
      packages:
        # Terminal Emulators
        - alacritty
        - ghostty

        # Shell
        - nu
        - dash
        - starship
        - atuin
        - zoxide

        # TUI
        - helix
        - yazi
        - btop
        - gdisk
        - btrfs-progs

        # Web
        - mullvad-vpn
        - mullvad-browser
        - zen-browser
        - brave-browser

        # Virtualization
        - qemu
        - edk2-ovmf
        - virt-manager
        - virt-viewer

        # Streaming
        - obs-studio

        # Compositors, Shells & Extra
        - niri
        - noctalia
        - gamescope
        - gamemode

        # Extra Plasma Stuff
        - plasma-oxygen
        - oxygen-icon-theme

    remove:
      packages:
        - firefox

  - type: signing
