name: bluebuild
on:
  schedule:
    - cron: "00 06 * * *"
  push:
    paths-ignore:
      - "**.md"

  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  bluebuild:
    name: Build OCI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - kinoite.yml
          - kinoite-nvidia-open.yml
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Extract kernel signing key
        shell: bash
        env:
          KERNEL_SIGNING_SECRET: ${{ secrets.KERNEL_SIGNING_SECRET }}
        run: echo "${KERNEL_SIGNING_SECRET}" | base64 -d > MOK.priv

      - name: Build Custom Image
        uses: blue-build/github-action@v1.12
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          skip_checkout: true
          maximize_build_space: true
